name: 'Anaconda-Action'
description: 'Build and publish conda packages'
author: 'fdiblen'
branding:
  icon: 'package'
  color: 'green'
inputs:
  env-name:  # id of input
    description: 'Envirenment name.'
    required: true
    default: 'environment.yml'
  env-file-name:  # id of input
    description: 'Envirenment file name.'
    required: true
    default: 'environment.yml'
  python-version:  # id of input
    description: 'Desired Python version to create a conda environment.'
    required: false
    default: 'default'
  channels:  # id of input
    description: 'Extra anaconda channels to use.'
    required: false
    default: ''
  activate-env:  # id of input
    description: 'Activate the new environment.'
    required: false
    default: 'true'
  publish:  # id of input
    description: 'Enable package publishing.'
    required: false
    default: 'false'
  publish-channel:  # id of input
    description: 'Channel to publish the anaconda package.'
    required: false
    default: ''
  anaconda-token:  # id of input
    description: 'Token to access to anaconda cloud.'
    required: false
    default: ''
outputs:
  time: # id of output
    description: 'The time the action was executed you.'
  conda_version:
    description: 'Conda version used in the action.'
  python_version:
    description: 'Python version used in the action.'
runs:
  using: 'node12'
  main: 'index.js'