name: 'Anaconda-Action'
description: 'Build and publish conda packages'
author: 'fdiblen'
branding:
  icon: 'package'
  color: 'green'
inputs:
  envFileName:  # id of input
    description: 'Envirenment file name'
    required: true
    default: 'environment.yml'
  pythonVersion:  # id of input
    description: 'Desired Python version to create a conda environment.'
    required: false
    default: 'default'
  channels:  # id of input
    description: 'Extra anaconda channels to use.'
    required: false
    default: ''
  activateEnv:  # id of input
    description: 'Activate the new environment.'
    required: false
    default: 'true'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  conda_version:
    description: 'Conda version'
  python_version:
    description: 'Python version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.envFileName }}