name: 'Test action'

on: [push]

jobs:
  test_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
        exclude:
          - os: macos-latest
            python-version: 3.8
          - os: windows-latest
            python-version: 3.6
    steps:
    - uses: actions/checkout@v2
    - name: Anaconda-Action
      id: step1
      uses: fdiblen/anaconda-action@0.1.7
      with:
        env-file-name: 'README.md'
    # Use the output from the `step1` step
    - name: Get the output time
      run: echo "The time was ${{ steps.step1.outputs.time }}"
    - name: Get the Conda version
      run: echo "The conda version is ${{ steps.step1.outputs.conda_version }}"
    - name: Get the Python version
      run: echo "The python version is ${{ steps.step1.outputs.python_version }}"
