name: 'Test action'

on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A simple test job
    steps:
    - name: Conda action
      id: step1
      uses: actions/Anaconda-Action@v1
      with:
        envFileName: 'env.yml'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.step1.outputs.time }}"